name: build-test
on: [pull_request]

jobs: 

build:

runs-on: ubuntu-latest strategy 
matrix: 
node: ['16']

steps 
-uses: actions/checkout@v2
-names: Setup Node 16
uses: actions/setup-node@v2
with: node-version 16.x
-run: npm intall 
-run: nmp run lint
